#if !canImport(ObjectiveC)
import XCTest

extension AsyncSemaphoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AsyncSemaphoreTests = [
        ("testDispatchSemaphore", testDispatchSemaphore),
        ("testSemaphoreWaitTimeoutWithTasksGreaterThanCount", testSemaphoreWaitTimeoutWithTasksGreaterThanCount),
        ("testSemaphoreWaitTimeoutWithTasksLessThanCount", testSemaphoreWaitTimeoutWithTasksLessThanCount),
        ("testSemaphoreWaitWithTasksEqualToCount", testSemaphoreWaitWithTasksEqualToCount),
        ("testSemaphoreWaitWithTasksGreaterThanCount", testSemaphoreWaitWithTasksGreaterThanCount),
        ("testSemaphoreWaitWithTasksLessThanCount", testSemaphoreWaitWithTasksLessThanCount),
        ("testSignaledSemaphoreWaitWithTasksGreaterThanCount", testSignaledSemaphoreWaitWithTasksGreaterThanCount),
        ("testUsageAsMutexWaitSuccessWithoutTimeout", testUsageAsMutexWaitSuccessWithoutTimeout),
        ("testUsageAsMutexWaitWithTimeout", testUsageAsMutexWaitWithTimeout),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AsyncSemaphoreTests.__allTests__AsyncSemaphoreTests),
    ]
}
#endif
