name: "Run Tests with Swift Package"

on:
  workflow_call:

jobs:
  # Test package with swift 5.6 on linux and windows
  swift-package:
    name: Run Swift Package Tests with swift version ${{ matrix.swift }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        swift: ['5.6']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check should proceed running steps
      id: precondition
      uses: ./.github/actions/condition
      with:
        files: |
          Sources/**/*.swift
          Tests/**/*
          Package*.swift
          .github/actions/setup/action.yml
          .github/workflows/swift-package.yml

    - name: Setup repository
      if: steps.precondition.outputs.proceed == 'true'
      uses: ./.github/actions/setup
      with:
        swift: ${{ matrix.swift }}

    - name: Run tests
      if: steps.precondition.outputs.proceed == 'true'
      run: npm run test

    - name: Swift Coverage Report
      if: |
        steps.precondition.outputs.proceed == 'true' &&
        matrix.swift == '5.6' &&
        github.event_name == 'push'
      uses: maxep/spm-lcov-action@0.3.1
      with:
        file-format: lcov
        output-file: ./coverage.lcov

    - name: Codecov upload
      if: |
        steps.precondition.outputs.proceed == 'true' &&
        matrix.swift == '5.6' &&
        github.event_name == 'push'
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
